"""adds ondelete cascade to vaultlog model

Revision ID: 551e90272bcd
Revises: b0cfbebfbef9
Create Date: 2025-06-30 16:36:20.065442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551e90272bcd'
down_revision = 'b0cfbebfbef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('vault_log_item_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('vault_log_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'vault_user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'vault_item', ['item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vault_log_user_id_fkey'), 'vault_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('vault_log_item_id_fkey'), 'vault_item', ['item_id'], ['id'])

    # ### end Alembic commands ###
