"""Add role to vault user model

Revision ID: b0cfbebfbef9
Revises: 1abef2b73628
Create Date: 2025-06-22 14:39:32.683140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cfbebfbef9'
down_revision = '1abef2b73628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
